### ISSUE TITLE
Expose API for setting up initial conditions?

### ISSUE THREAD

**Issue by xiaoweiz** [AnthonyEbert/queuecomputer#17]
I'd like to first congratulate this promising package. Queueing simulation is notoriously slow. I've tried `simpy` of Python as well as `SimJulia` of Julia. But neither is very satisfying in terms of speed and ease-of-use. This package shows great potential and I'd very much try it in my own research. I haven't gone through the package in details so bear with me if my question is trivial. 

A particular computational challenge in queueing simulation is the steady-state simulation, especially if the traffic intensity of the system is high. In such situations, the specification of the initial conditions (e.g. number of customers in the system / busy servers at the beginning of a simulation path) is critical for the overall simulation quality. For instance, if the system is heavily utilized, it is often not a good idea to start each simulation path with empty system. So it'd be very nice if there is a way in the package to allow users to specify the initial conditions easily.

**Comment by AnthonyEbert** [comment]
Hi Xiaoweiz, 

Thank you for your feedback! Specification of initial conditions is something not yet implemented in this package. It's something that I'm thinking of adding. 

However, there is a "hack" you can do using the version currently available on CRAN, 0.6.1. If you want 50 customers in the system at the beginning of the simulation put 50 customers with arrival time zero and then move the rest of your customers forward. 

What do you think of that?

**Comment by xiaoweiz** [comment]
Yes. I read your recent paper on Arxiv yesterday and implemented exactly this approach in Julia.
