### ISSUE TITLE
multi-processor

### ISSUE THREAD

**Issue by nergiszaim** [AnthonyEbert/queuecomputer#29]
Is there a development where servers that support multiprocessor systems (such as GPUs) can also be applied to this package?

**Comment by AnthonyEbert** [comment]
Sorry, I just saw this issue today. Do you mean simulating a multiprocessor system or running this code on a multiprocessor system? 

If you mean the former, yes, it can simulate multi-server settings. Using `queue` or `queue_step`, set `servers=n` where `n` is the number of servers you wish to simulate. 

If you mean the latter, no, at the moment the package is not written to run in parallel.

**Comment by AnthonyEbert** [comment]
However, if you wish to run multiple independent queue simulations in parallel - Here is an explanation that I wrote.  

https://stackoverflow.com/a/70866183/4745348
