### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by soliverc** [AnthonyEbert/queuecomputer#36]
Hi there, 

I'm not certain on how to set up the simulation using `queue_step`. There aren't many of tutorials for this package. Also my R skills are a bit rusty. 

I'm following this guide: https://cran.r-project.org/web/packages/queuecomputer/vignettes/Howto.html

For setting up the exponential service vector for `n=100`:

`service <- rexp(100)`

Let's say the service time is 10 minutes i.e. it takes 10 minutes to serve one customer. 

Should this be: `service <- rexp(100,10)` ?

or should it be converted to a rate of customers per minute? So `1/10 = 0.1` customers per minute:

`service <- rexp(100,0.1)`

I am using this in python with the rpy2 package by the way. Everything is working fine.

**Comment by AnthonyEbert** [comment]
Hi sorry for the late reply. 

The function rexp is not part of queuecomputer (sorry if that's obvious!), it's the function in R for generating exponentially distributed values. The only thing queuecomputer sees is the vector of numbers it generates. 

Anyway... in answer to your question for exponentially distributed service times with an average 10 minutes, the correct expression is 

`service <- rexp(100,0.1)`

For another example see Section 8 of our paper https://www.jstatsoft.org/index.php/jss/article/view/v095i05/v95i05.pdf

I see your point. I should make some more tutorials. Thanks! Please ask if there's any other questions.
